import { Microsoft365Products } from "../enums/microsoft-365-products";

export default class SkuConstants {
    static readonly TEAMS_SKU_PART_NUMBERS: string[] = ['MCOCAP', 'MCOCAP_GOV', 'MICROSOFT_REMOTE_ASSIST', 'MICROSOFT_REMOTE_ASSIST_HOLOLENS', 'M365EDU_A3_FACULTY', 'M365EDU_A3_STUDENT', 'M365EDU_A3_STUUSEBNFT', 'M365EDU_A3_STUUSEBNFT_RPA1', 'M365EDU_A5_FACULTY', 'M365EDU_A5_STUDENT', 'M365EDU_A5_STUUSEBNFT', 'M365EDU_A5_NOPSTNCONF_STUUSEBNFT', 'O365_BUSINESS_PREMIUM', 'SPB', 'SPE_E3', 'SPE_E3_RPA1', 'SPE_E3_USGOV_DOD', 'SPE_E3_USGOV_GCCHIGH', 'SPE_E5', 'DEVELOPERPACK_E5', 'SPE_E5_NOPSTNCONF', 'M365_F1', 'SPE_F1', 'M365_F1_GOV', 'M365_G5_GCC', 'M365_G3_GOV', 'TEAMS_FREE', 'TEAMS_EXPLORATORY', 'MEETING_ROOM', 'MEETING_ROOM_NOAUDIOCONF', 'MS_TEAMS_IW', 'STANDARDWOFFPACK_FACULTY', 'STANDARDWOFFPACK_IW_FACULTY', 'STANDARDWOFFPACK_STUDENT ', 'STANDARDWOFFPACK_IW_STUDENT', 'ENTERPRISEPACKPLUS_FACULTY', 'ENTERPRISEPACKPLUS_STUDENT', 'ENTERPRISEPREMIUM_FACULTY', 'ENTERPRISEPREMIUM_STUDENT', 'TEAMS_COMMERCIAL_TRIAL', 'STANDARDPACK', 'ENTERPRISEPACK', 'ENTERPRISEPACK_USGOV_DOD', 'ENTERPRISEPACK_USGOV_GCCHIGH', 'ENTERPRISEPREMIUM', 'DESKLESSPACK', 'STANDARDPACK_GOV', 'ENTERPRISEPACK_GOV', 'MTR_PREM'];

    static readonly OFFICE_SKU_PART_NUMBERS: string[] = ['DYN365_ENTERPRISE_PLAN1', 'DYN365_CUSTOMER_SERVICE_PRO', 'DYN365_ENTERPRISE_CASE_MANAGEMENT', 'DYN365_ENTERPRISE_CUSTOMER_SERVICE', 'DYN365_ENTERPRISE_SALES_CUSTOMERSERVICE', 'DYN365_ENTERPRISE_SALES', 'D365_SALES_PRO ', 'DYN365_ENTERPRISE_TEAM_MEMBERS', 'DYN365_TEAM_MEMBERS', 'M365EDU_A3_FACULTY', 'M365EDU_A3_STUDENT', 'M365EDU_A3_STUUSEBNFT', 'M365EDU_A3_STUUSEBNFT_RPA1', 'M365EDU_A5_FACULTY', 'M365EDU_A5_STUDENT', 'M365EDU_A5_STUUSEBNFT', 'M365EDU_A5_NOPSTNCONF_STUUSEBNFT', 'O365_BUSINESS', 'SMB_BUSINESS', 'OFFICESUBSCRIPTION', 'OFFICESUBSCRIPTION_STUDENT', 'OFFICESUBSCRIPTION_FACULTY', 'O365_BUSINESS_ESSENTIALS', 'SMB_BUSINESS_ESSENTIALS', 'O365_BUSINESS_PREMIUM', 'SMB_BUSINESS_PREMIUM', 'SPB', 'SPE_E3', 'SPE_E3_RPA1', 'SPE_E3_USGOV_DOD', 'SPE_E3_USGOV_GCCHIGH', 'SPE_E5', 'DEVELOPERPACK_E5', 'SPE_E5_NOPSTNCONF', 'SPE_F1', 'M365_F1_GOV', 'M365_G5_GCC', 'M365_G3_GOV', 'TEAMS_EXPLORATORY', 'MS_TEAMS_IW', 'STANDARDWOFFPACK_FACULTY', 'STANDARDWOFFPACK_IW_FACULTY', 'STANDARDWOFFPACK_STUDENT ', 'STANDARDWOFFPACK_IW_STUDENT', 'ENTERPRISEPACKPLUS_FACULTY', 'ENTERPRISEPACKPLUS_STUDENT', 'ENTERPRISEPREMIUM_FACULTY', 'ENTERPRISEPREMIUM_STUDENT', 'TEAMS_COMMERCIAL_TRIAL', 'STANDARDPACK', 'STANDARDWOFFPACK', 'ENTERPRISEPACK', 'DEVELOPERPACK', 'ENTERPRISEPACK_USGOV_DOD', 'ENTERPRISEPACK_USGOV_GCCHIGH', 'ENTERPRISEWITHSCAL', 'ENTERPRISEPREMIUM', 'ENTERPRISEPREMIUM_NOPSTNCONF', 'DESKLESSPACK', 'STANDARDPACK_GOV', 'ENTERPRISEPACK_GOV', 'ENTERPRISEPREMIUM_GOV', 'MIDSIZEPACK', 'LITEPACK_P2', 'WACONEDRIVESTANDARD', 'WACONEDRIVEENTERPRISE', 'PROJECTESSENTIALS', 'PROJECTESSENTIALS_GOV', 'PROJECTPREMIUM', 'PROJECTONLINE_PLAN_1', 'PROJECTONLINE_PLAN_2', 'PROJECTPROFESSIONAL', 'PROJECT_PLAN3_DEPT', 'PROJECTPROFESSIONAL_GOV', 'PROJECTPREMIUM_GOV'];

    static readonly ONEDRIVE_SKU_PART_NUMBERS: string[] = ['O365_BUSINESS', 'SMB_BUSINESS', 'OFFICESUBSCRIPTION', 'OFFICESUBSCRIPTION_STUDENT', 'OFFICESUBSCRIPTION_FACULTY', 'WACONEDRIVESTANDARD', 'WACONEDRIVEENTERPRISE', 'VISIO_PLAN1_DEPT', 'VISIO_PLAN2_DEPT', 'VISIOONLINE_PLAN1', 'VISIOCLIENT', 'VISIOCLIENT_GOV'];

    static readonly SHAREPOINT_SKU_PART_NUMBERS: string[] = ['DYN365_ENTERPRISE_PLAN1', 'DYN365_CUSTOMER_SERVICE_PRO', 'DYN365_ENTERPRISE_CASE_MANAGEMENT', 'DYN365_ENTERPRISE_CUSTOMER_SERVICE', 'DYN365_ENTERPRISE_SALES_CUSTOMERSERVICE', 'DYN365_ENTERPRISE_SALES', 'DYN365_ENTERPRISE_TEAM_MEMBERS', 'DYN365_TEAM_MEMBERS', 'M365EDU_A3_FACULTY', 'M365EDU_A3_STUDENT', 'M365EDU_A3_STUUSEBNFT', 'M365EDU_A3_STUUSEBNFT_RPA1', 'M365EDU_A5_FACULTY', 'M365EDU_A5_STUDENT', 'M365EDU_A5_STUUSEBNFT', 'M365EDU_A5_NOPSTNCONF_STUUSEBNFT', 'O365_BUSINESS_ESSENTIALS', 'SMB_BUSINESS_ESSENTIALS', 'O365_BUSINESS_PREMIUM', 'SMB_BUSINESS_PREMIUM', 'SPB', 'SPE_E3', 'SPE_E3_RPA1', 'SPE_E3_USGOV_DOD', 'SPE_E3_USGOV_GCCHIGH', 'SPE_E5', 'DEVELOPERPACK_E5', 'SPE_E5_NOPSTNCONF', 'M365_F1', 'SPE_F1', 'M365_F1_GOV', 'M365_G5_GCC', 'M365_F1_COMM', 'M365_G3_GOV', 'TEAMS_FREE', 'TEAMS_EXPLORATORY', 'MS_TEAMS_IW', 'STANDARDWOFFPACK_FACULTY', 'STANDARDWOFFPACK_IW_FACULTY', 'STANDARDWOFFPACK_STUDENT ', 'STANDARDWOFFPACK_IW_STUDENT', 'ENTERPRISEPACKPLUS_FACULTY', 'ENTERPRISEPACKPLUS_STUDENT', 'ENTERPRISEPREMIUM_FACULTY', 'ENTERPRISEPREMIUM_STUDENT', 'SHAREPOINTSTORAGE_GOV', 'TEAMS_COMMERCIAL_TRIAL', 'STANDARDPACK', 'STANDARDWOFFPACK', 'ENTERPRISEPACK', 'DEVELOPERPACK', 'ENTERPRISEPACK_USGOV_DOD', 'ENTERPRISEPACK_USGOV_GCCHIGH', 'ENTERPRISEWITHSCAL', 'ENTERPRISEPREMIUM', 'ENTERPRISEPREMIUM_NOPSTNCONF', 'DESKLESSPACK', 'STANDARDPACK_GOV', 'ENTERPRISEPACK_GOV', 'ENTERPRISEPREMIUM_GOV', 'MIDSIZEPACK', 'LITEPACK', 'LITEPACK_P2', 'PROJECTESSENTIALS', 'PROJECTESSENTIALS_GOV', 'PROJECTPREMIUM', 'PROJECTONLINE_PLAN_1', 'PROJECTONLINE_PLAN_2', 'PROJECT_P1', 'PROJECT_PLAN1_DEPT', 'PROJECTPROFESSIONAL', 'PROJECT_PLAN3_DEPT', 'PROJECTPROFESSIONAL_GOV', 'PROJECTPREMIUM_GOV', 'SHAREPOINTSTANDARD', 'SHAREPOINTENTERPRISE'];

    static readonly MAPPING_SKU_PRODUCTS = {
        'MCOCAP': [Microsoft365Products.Teams],
        'MCOCAP_GOV': [Microsoft365Products.Teams],
        'MICROSOFT_REMOTE_ASSIST': [Microsoft365Products.Teams],
        'MICROSOFT_REMOTE_ASSIST_HOLOLENS': [Microsoft365Products.Teams],
        'M365EDU_A3_FACULTY': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'M365EDU_A3_STUDENT': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'M365EDU_A3_STUUSEBNFT': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'M365EDU_A3_STUUSEBNFT_RPA1': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'M365EDU_A5_FACULTY': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'M365EDU_A5_STUDENT': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'M365EDU_A5_STUUSEBNFT': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'M365EDU_A5_NOPSTNCONF_STUUSEBNFT': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'O365_BUSINESS_PREMIUM': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'SPB': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'SPE_E3': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'SPE_E3_RPA1': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'SPE_E3_USGOV_DOD': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'SPE_E3_USGOV_GCCHIGH': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'SPE_E5': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'DEVELOPERPACK_E5': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'SPE_E5_NOPSTNCONF': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'M365_F1': [Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'SPE_F1': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'M365_F1_GOV': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'M365_G5_GCC': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'M365_G3_GOV': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'TEAMS_FREE': [Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'TEAMS_EXPLORATORY': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'MEETING_ROOM': [Microsoft365Products.Teams],
        'MEETING_ROOM_NOAUDIOCONF': [Microsoft365Products.Teams],
        'MS_TEAMS_IW': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'STANDARDWOFFPACK_FACULTY': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'STANDARDWOFFPACK_IW_FACULTY': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'STANDARDWOFFPACK_STUDENT ': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'STANDARDWOFFPACK_IW_STUDENT': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'ENTERPRISEPACKPLUS_FACULTY': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'ENTERPRISEPACKPLUS_STUDENT': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'ENTERPRISEPREMIUM_FACULTY': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'ENTERPRISEPREMIUM_STUDENT': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'TEAMS_COMMERCIAL_TRIAL': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'STANDARDPACK': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'ENTERPRISEPACK': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'ENTERPRISEPACK_USGOV_DOD': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'ENTERPRISEPACK_USGOV_GCCHIGH': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'ENTERPRISEPREMIUM': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'DESKLESSPACK': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'STANDARDPACK_GOV': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'ENTERPRISEPACK_GOV': [Microsoft365Products.Office, Microsoft365Products.SharePoint, Microsoft365Products.Teams],
        'MTR_PREM': [Microsoft365Products.Teams],
        'DYN365_ENTERPRISE_PLAN1': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'DYN365_CUSTOMER_SERVICE_PRO': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'DYN365_ENTERPRISE_CASE_MANAGEMENT': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'DYN365_ENTERPRISE_CUSTOMER_SERVICE': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'DYN365_ENTERPRISE_SALES_CUSTOMERSERVICE': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'DYN365_ENTERPRISE_SALES': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'D365_SALES_PRO ': [Microsoft365Products.Office],
        'DYN365_ENTERPRISE_TEAM_MEMBERS': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'DYN365_TEAM_MEMBERS': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'O365_BUSINESS': [Microsoft365Products.Office, Microsoft365Products.OneDrive],
        'SMB_BUSINESS': [Microsoft365Products.Office, Microsoft365Products.OneDrive],
        'OFFICESUBSCRIPTION': [Microsoft365Products.Office, Microsoft365Products.OneDrive],
        'OFFICESUBSCRIPTION_STUDENT': [Microsoft365Products.Office, Microsoft365Products.OneDrive],
        'OFFICESUBSCRIPTION_FACULTY': [Microsoft365Products.Office, Microsoft365Products.OneDrive],
        'O365_BUSINESS_ESSENTIALS': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'SMB_BUSINESS_ESSENTIALS': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'SMB_BUSINESS_PREMIUM': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'STANDARDWOFFPACK': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'DEVELOPERPACK': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'ENTERPRISEWITHSCAL': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'ENTERPRISEPREMIUM_NOPSTNCONF': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'ENTERPRISEPREMIUM_GOV': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'MIDSIZEPACK': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'LITEPACK_P2': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'WACONEDRIVESTANDARD': [Microsoft365Products.Office, Microsoft365Products.OneDrive],
        'WACONEDRIVEENTERPRISE': [Microsoft365Products.Office, Microsoft365Products.OneDrive],
        'PROJECTESSENTIALS': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'PROJECTESSENTIALS_GOV': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'PROJECTPREMIUM': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'PROJECTONLINE_PLAN_1': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'PROJECTONLINE_PLAN_2': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'PROJECTPROFESSIONAL': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'PROJECT_PLAN3_DEPT': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'PROJECTPROFESSIONAL_GOV': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'PROJECTPREMIUM_GOV': [Microsoft365Products.Office, Microsoft365Products.SharePoint],
        'VISIO_PLAN1_DEPT': [Microsoft365Products.OneDrive],
        'VISIO_PLAN2_DEPT': [Microsoft365Products.OneDrive],
        'VISIOONLINE_PLAN1': [Microsoft365Products.OneDrive],
        'VISIOCLIENT': [Microsoft365Products.OneDrive],
        'VISIOCLIENT_GOV': [Microsoft365Products.OneDrive],
        'M365_F1_COMM': [Microsoft365Products.SharePoint],
        'SHAREPOINTSTORAGE_GOV': [Microsoft365Products.SharePoint],
        'LITEPACK': [Microsoft365Products.SharePoint],
        'PROJECT_P1': [Microsoft365Products.SharePoint],
        'PROJECT_PLAN1_DEPT': [Microsoft365Products.SharePoint],
        'SHAREPOINTSTANDARD': [Microsoft365Products.SharePoint],
        'SHAREPOINTENTERPRISE': [Microsoft365Products.SharePoint]
    }
}